### PR TITLE
Update de.json

### PR DESCRIPTION
**Pull request by AbdulkarimAljubouri**
Hallo!,
so this is DEUTSCH language in form, you can check it variables and constants if there is any problem let me know. 
MIT FREUNDLICHEN GRÜßEN

### CODE REVIEW

**Comment by gaodeng** [comment]
Thank you very much!

Can you please provide the following information to be displayed in the language settings screen

- Name or nickname displayed on the acknowledgement screen
- A link - a link to your website or a link to your social network twitter, Instagram, etc.

**Comment by AbdulkarimAljubouri** [comment]
> Thank you very much!
> 
> 
> 
> Can you please provide the following information to be displayed in the language settings screen
> 
> 
> 
> - Name or nickname displayed on the acknowledgement screen
> 
> - A link - a link to your website or a link to your social network twitter, Instagram, etc.
> 
> 
> 
> 
> 
> 
> 
> 

You welcome sir,
my Name: Abdulkarim Aljubouri.
my Nickname: Abdu Aljubouri

Instagram reference URL link:
[https://www.instagram.com/abdulkarim.aljubouri/]()
Twitter reference URL link:
[https://twitter.com/AbduAljubouri]()

**Comment by AbdulkarimAljubouri** [comment]
Also as plus please add my GitHub URL link: https://github.com/AbdulkarimAljubouri

**Comment by gaodeng** [comment]
Hi, since there is only one link designed for this location, I think we should add your github link and then you can customize the github homepage and add other links to the github homepage.
For example, like Caneco https://github.com/caneco/

**Pull request merged**
